name: Sync upstream

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with upstream
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://github.com/OpenVeraTeam/LiveMoments.git"
          source_branch: ${{ github.event.repository.default_branch }}
          destination_branch: ${{ github.event.repository.default_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
